name: Golden Owl CI/CD

on:
  push:
    branches:
      - "master"
      - "feature/**"

jobs:
  # Job 1: Build và Test ứng dụng Node.js
  build-and-test:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 

      - name: Install dependencies
        run: cd src && npm i

      - name: Run tests
        run: cd src && npm test 

  # Job 2: Build và Push Docker image lên Docker Hub
  build-and-push-docker:

    if: github.ref == 'refs/heads/main'
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: . 
          file: ./Dockerfile 
          push: true 
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/golden-owl-app:latest