name: Continuous Integration

on:
  push:
    branches:
      - "feature/**"
  pull_request:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 24

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Setup NodeJS
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: src/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: ESLint
        run: npm run lint:check

      - name: Run Tests
        run: npm test

  hadolint:
    name: Dockerfile Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Hadolint
        uses: hadolint/hadolint-action@v3.2.0
        with:
          dockerfile: Dockerfile
          verbose: true

  dependency-scan:
    name: Dependency Scan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: src/package-lock.json

      - run: npm ci

      - name: npm audit
        run: npm audit --omit=dev --audit-level=high

  filesystem-scan:
    name: Run Trivy vulnerability scanner in fs mode
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          scan-ref: .
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 1
